project_id = "qvamzeepjzqndakhjpjg"

[functions.stripe-webhook]
verify_jwt = false

[functions.send-review-notification]
verify_jwt = false

[functions.complete-setup]
verify_jwt = true

[functions.create-invitation]
verify_jwt = true

[functions.get-invitation-data]
verify_jwt = false

[functions.create-public-document]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = true

[functions.compute-requirements]
verify_jwt = true

[functions.demo-reset]
verify_jwt = false