// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eodnsbbdkqsoreazpday.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvZG5zYmJka3Fzb3JlYXpwZGF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTk4MDgsImV4cCI6MjA3MjgzNTgwOH0.Rh5V2Yi__5a8yMLhebnGZpy4w6hePyl_c1iMl6JpLNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});