// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvamzeepjzqndakhjpjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2YW16ZWVwanpxbmRha2hqcGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjYxODMsImV4cCI6MjA3Mjg0MjE4M30.j4IsZ4wvBePgh1moBRBCFFum0t8uGDTVRsNlNjYK3D8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});